#!/usr/bin/env python3
"""
create.py: Module for creating products and collections in the Shopify store for the Buildify project.

This module contains functions to create new products and collections on Shopify using the Shopify API.
The creation process involves defining product details and organizing them into collections based on the
clusters generated by the clustering algorithm.
"""

from shopify import ShopifyAPI

def create_product(shopify_api, product_data):
    """
    Create a new product in the Shopify store.

    :param shopify_api: An instance of the ShopifyAPI class for making API requests.
    :param product_data: A dictionary containing the product details.
    :return: The response from the Shopify API.
    """
    # Define the product payload for the API request
    product_payload = {
        "product": {
            "title": product_data['title'],
            "body_html": product_data['description'],
            "vendor": product_data['vendor'],
            "product_type": product_data['type'],
            "tags": product_data['tags']
            # Add additional product details here
        }
    }

    # Create the product using the Shopify API
    response = shopify_api.create_product(product_payload)
    return response

def create_collection(shopify_api, collection_name, product_ids):
    """
    Create a new collection in the Shopify store and add products to it.

    :param shopify_api: An instance of the ShopifyAPI class for making API requests.
    :param collection_name: The name of the new collection.
    :param product_ids: A list of product IDs to be added to the collection.
    :return: The response from the Shopify API.
    """
    # Define the collection payload for the API request
    collection_payload = {
        "custom_collection": {
            "title": collection_name,
            "collects": [{"product_id": pid} for pid in product_ids]
            # Add additional collection details here
        }
    }

    # Create the collection using the Shopify API
    response = shopify_api.create_collection(collection_payload)
    return response

# Example usage
if __name__ == "__main__":
    # Initialize the Shopify API (replace with actual credentials)
    api = ShopifyAPI(api_key='your_api_key', password='your_api_password', store_url='your_store_url')

    # Example product data (this would be replaced with real data)
    example_product = {
        'title': 'Eco-friendly Water Bottle',
        'description': '<strong>Save the planet</strong> one sip at a time with our reusable bottles.',
        'vendor': 'EcoGoods',
        'type': 'Bottle',
        'tags': ['eco-friendly', 'water', 'bottle']
    }

    # Create a new product
    product_response = create_product(api, example_product)
    print(f"Product creation response: {product_response}")

    # Example collection name and product IDs (this would be replaced with real data)
    example_collection_name = 'Eco-Friendly Collection'
    example_product_ids = [123456789, 987654321]

    # Create a new collection
    collection_response = create_collection(api, example_collection_name, example_product_ids)
    print(f"Collection creation response: {collection_response}")
